name = "JAMS"
uuid = "e037fcc2-89bb-496d-a467-a0483cd5c74c"
authors = ["pyrex41 <reub.brooks@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
